apiVersion: apps/v1
kind: Deployment
metadata:
  name: qbittorrent
  namespace: servarr
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: qbittorrent
  template:
    metadata:
      labels:
        app: qbittorrent
    spec:
      containers:
        - name: qbittorrent
          image: lscr.io/linuxserver/qbittorrent:libtorrentv1
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: TZ
              value: Europe/Ljubljana
            - name: WEBUI_PORT
              value: "8080"
            - name: TORRENTING_PORT
              value: "30881"
          ports:
            - containerPort: 8080
            - containerPort: 30881
              protocol: TCP
            - containerPort: 30881
              protocol: UDP
          volumeMounts:
            - name: config
              mountPath: /config
            - name: torrents
              mountPath: /data/torrents
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: qbittorrent-config
        - name: torrents
          nfs:
            server: 10.0.0.104
            path: /mnt/serve/starr-stack/data/torrents
