fullnameOverride: qbittorrent

controllers:
  main:
    type: deployment
    strategy: Recreate
    containers:
      main:
        image:
          repository: lscr.io/linuxserver/qbittorrent
          tag: 20.04.1
        env:
          PUID: "1000"
          PGID: "1000"
          TZ: Europe/Ljubljana
          WEBUI_PORT: "8080"
          TORRENTING_PORT: "30881"

persistence:
  config:
    type: persistentVolumeClaim
    existingClaim: qbittorrent-config
    globalMounts:
      - path: /config
  torrents:
    type: nfs
    server: 10.0.0.104
    path: /mnt/serve/starr-stack/data/torrents
    globalMounts:
      - path: /data/torrents

route:
  app:
    parentRefs:
      - name: traefik-gateway
        namespace: traefik
        sectionName: websecure
    hostnames:
      - qb.talos-cluster.local.obleey.com
    rules:
      - backendRefs:
          - name: qbittorrent
            port: 8080
