fullnameOverride: qbittorrent

controllers:
  main:
    type: deployment
    strategy: Recreate
    containers:
      main:
        image:
          repository: lscr.io/linuxserver/qbittorrent
          tag: 20.04.1
        env:
          PUID: "1000"
          PGID: "1000"
          TZ: Europe/Ljubljana
          WEBUI_PORT: "8080"
          TORRENTING_PORT: "30881"
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            memory: 2Gi

persistence:
  config:
    type: persistentVolumeClaim
    existingClaim: qbittorrent-config
    globalMounts:
      - path: /config
  torrents:
    type: nfs
    server: 10.0.0.104
    path: /mnt/serve/starr-stack/data/torrents
    globalMounts:
      - path: /data/torrents

service:
  app:
    controller: main
    type: NodePort
    ports:
      webui:
        primary: true
        port: 8080
        protocol: TCP
      torrenting-tcp:
        port: 30881
        protocol: TCP
        nodePort: 30881
      torrenting-udp:
        port: 30881
        protocol: UDP
        nodePort: 30881

route:
  app:
    parentRefs:
      - name: traefik-gateway
        namespace: traefik
        sectionName: websecure
    hostnames:
      - qb.talos-cluster.local.obleey.com
    rules:
      - filters:
          - type: ExtensionRef
            extensionRef:
              group: traefik.io
              kind: Middleware
              name: authelia-forward-auth
        backendRefs:
          - name: qbittorrent
            port: 8080
