apiVersion: v1
kind: Service
metadata:
  name: qbittorrent
  namespace: servarr
spec:
  type: NodePort
  selector:
    app: qbittorrent
  ports:
    - name: torrenting-tcp
      port: 30881
      targetPort: 30881
      nodePort: 30881 # External P2P Access
      protocol: TCP
    - name: torrenting-udp
      port: 30881
      targetPort: 30881
      nodePort: 30881 # External P2P Access
      protocol: UDP
