apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - bazarr/app.yaml
  - byparr/app.yaml
  - jellyfin/app.yaml
  - kubeseal-webgui/app.yaml
  - notifiarr/app.yaml
  - plex/app.yaml
  - prowlarr/app.yaml
  - qbittorrent/app.yaml
  - radarr/app.yaml
  - seerr/app.yaml
  - sonarr/app.yaml
  - unpackerr/app.yaml
