apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: victorialogs
  namespace: argocd
  labels:
    argocd.argoproj.io/managed-by: talos-cluster
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: https://victoriametrics.github.io/helm-charts
      chart: victoria-logs-single
      targetRevision: 0.9.3
      helm:
        valueFiles:
          - $values/deployments/observability/victorialogs/vl-values.yaml
    - repoURL: https://github.com/obleey/talos-homelab
      targetRevision: HEAD
      ref: values
      path: deployments/observability/victorialogs
      directory:
        exclude: "{app.yaml,vl-values.yaml}"
  destination:
    server: https://kubernetes.default.svc
    namespace: observability
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
