apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  project: default
  sources:
    - repoURL: https://argoproj.github.io/argo-helm
      chart: argo-cd
      targetRevision: 9.5.3
      helm:
        valueFiles:
          - $values/deployments/infrastructure/argocd/argocd-values.yaml
    - repoURL: https://github.com/obleey/talos-homelab
      targetRevision: HEAD
      ref: values
      path: deployments/infrastructure/argocd
      directory:
        exclude: "{app.yaml,argocd-values.yaml}"
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
