configs:
  params:
    server.insecure: true
  cm:
    url: https://argocd.talos-cluster.local.obleey.com
    timeout.reconciliation: 30s
    resource.customizations.ignoreDifferences.argoproj.io_Application: |
      jqPathExpressions:
        - .metadata.annotations["argocd.argoproj.io/tracking-id"]

notifications:
  enabled: true
  secret:
    create: false
  cm:
    create: true
    context: |
      argocdUrl: https://argocd.talos-cluster.local.obleey.com
      clusterName: talos-cluster
  notifiers:
    service.slack: |
      token: $slack-token

  templates:
    template.app-sync-failed: |
      message: |
        :red_circle: *[TALOS-CLUSTER]* *{{.app.metadata.name | upper}}* sync failed!
        Repo: {{.app.spec.source.repoURL}}
        Error: {{.app.status.operationState.message}}

  triggers:
    trigger.on-sync-failed: |
      - when: app.status.operationState != nil and app.status.operationState.phase in ['Error', 'Failed']
        send: [app-sync-failed]
      - when: app.status.sync.status == 'Unknown'
        send: [app-sync-failed]

  subscriptions:
    - recipients:
        - slack:#deployments
      triggers:
        - on-sync-failed
