---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: argocd-notifications-secret
  namespace: argocd
spec:
  encryptedData:
    slack-token: AgCcfNrcvihX23hB+Brbg0locsHjHp4RJPIl9Nrsp3CEkpVy3Z0wQCeEb/+L+m2iKP79+b+MX3qFdGsxG0lrgC2o5UIAtJUoE7eYOjWR+HkSMImCUeeWCc+ahYVDQNq0r+8cTJWKcg9NukoFEB6oX6Ij/Zxwen0BRmKA+qO+UXUKQEpO02nC+7HsLUYdEuxgLhoJ7nEdopXRqx10iNlHmwpvfJ4ZlhuzijUC4J3cTsVGKX+ZyBKgTK5O3LC3WF25wQ9mZSeiqx66iRr+hSiUbDUK6xMNGgPlsgzixfkqN8Fx/oKvUfAAtoY44+au3o8ppwrYiYI0SwtGMZ6ABmjxq7Xqdk6OfqkBUMmzGTu450XC5jkvnXBQ+dWWAhKppdIYvnKfzUR+83JFbiJpAfMOYTECl3mwcaO4IiAZ4uWcPxkc/MBHMM7uN7iwKGw/0IGB64k6sDb0453Ya2L/EXleQA3TPaZltBr1iHDvNifI4jV/C+fFWU7F828N/3FLdXtmb+iDSutZBajfTDNSGc/YOYIV9qpkwleOw3iQ7s5NGitFcVzBpto4/BiPeVIgYShkzn2Xh9M1P3bNPJTTzpb6ZABmBLIw9+soTMvXKVzcORKTydKeCPUFqS/lyYtR5BnzXHQ8ofcww764fePZWe+zQgMJHsPCcTqzFUv1vcQ+7KV+kgEdOGqjpDno0lpGAIIcW9TQY1oKJeYQRB/7+2F3bm0dKr/0KMyNd5Xr0RVIIRcjb2RumeTSJhBkF26IDHQVbIGCwgFqrUuLk8ddTg==
  template:
    metadata:
      name: argocd-notifications-secret
      namespace: argocd
    type: Opaque
