configs:
  params:
    server.insecure: true
  cm:
    url: https://argocd.talos-cluster.local.obleey.com

notifications:
  enabled: true
  secret:
    create: false
  cm:
    create: true
    context: |
      argocdUrl: https://argocd.talos-cluster.local.obleey.com
      clusterName: talos-cluster
  notifiers:
    service.slack: |
      token: $slack-token

  templates:
    template.app-sync-failed: |
      message: |
        :red_circle: *[talos-cluster]* *{{.app.metadata.name}}* sync failed!
        Repo: {{.app.spec.source.repoURL}}
        Error: {{.app.status.operationState.message}}

  triggers:
    trigger.on-sync-failed: |
      - when: app.status.operationState.phase in ['Error', 'Failed']
        send: [app-sync-failed]

  subscriptions:
    - recipients:
        - slack:#deployments
      triggers:
        - on-sync-failed
