---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: argocd-notifications-secret
  namespace: argocd
spec:
  encryptedData:
    slack-token: AgBu2yRnmJnZf+rQEP+F9ELSupSl9JRDTWsse7B63K3V6054xublQr9n/0jN/XR+13VKBjqo/ZN7OZHVNscX7Uq6abVaHDuPLcbIQhKl/ZCM6WvkKyy2xPWSNlPn3ba62Wo661rZNY1VuiqTEFDlOheBCKEMBTJGnko6L1c4uZgeaO3MAvgFP9+kdJ0jg2sM3+Op1qplRb38Z72C6ybxTgzZhbY+IlTi7WBOiVFqBimmspXsOQrN3KPdZt6y043ND26HZl7jK9VXqgLK9IxfPYcC3+/gV1pkpbuHNWZxA+HY9ThGDQ69XNWXQT7ug6B/z2rcdpKK8WbyzWnZSnD6MDyJzyTiXPp7TJ65E69JmkKxe4cIxdyoUY6CRA0jYncPnczrR3BDIo+MBqEJToK3l55Yp4rn97Jf9uUqu7qus+qh6DecNJpKiESpm9ZHlEuI6ZlDKWtOw2V9Bstoe7u7XDSa8pSAJsgWm+sS3RWjXcsITmETM8P7i/+SLRsorOxCfqJrZ5BBGS9jgyuYvfT8KQR4ecIQOW3UyHpi9hXeZis1kQ3xNjzzRKRLmL59kXZDoSP4mQ7PKFglNRfQYcSvtm1+3GudLtXa3MxvNLVlFD6fn1kPOvgw9A53I42z420QQ7QwNnGEhOFzYpD+PGqvzGnSNQaDmzyacx2STgprfFi9brt/Q/CuTtsiTgMkLXq/H6zVbfyKpg68CDXlBLaw/q8cQq78aRnbSpyifaO0BexA54BXEwu4vpago5KajAyHPog7uFtiOUEhO0W/UQ==
  template:
    metadata:
      name: argocd-notifications-secret
      namespace: argocd
    type: Opaque
