apiVersion: v1
kind: Secret
metadata:
  name: ghcr-netbird-helm
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: helm
  name: ghcr-netbird
  url: oci://ghcr.io/netbirdio/helm-charts
  enableOCI: "true"
