---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: git-creds
  namespace: argocd
spec:
  encryptedData:
    password: AgB/yG7GYbLFszN4ibhUeTGzmDEftYT3aYDv1APxduzSOsgTFYfOVq0skm5cxPdw58jV2FIjHJNY/lcISTuQe+WEO838okOeFvlWhlDS62Ciy2xNvEENYR4xLsJbqY7J5PLLaIc64baB8VlFckNsaWnZLRIZ+f+J7Am+GZR0Xjz0AImdKJ/SXphWVa6hBap5tnHzECJCJVf2J+X8etg8z6sF3yjqAhDFYGK26tfy3NAWyV1EUNc98zAVC4uKuEITwCJxuUaYEMJjJnRgoJxdxDwTTd6nLbl9qm0laz9YzhS2eUk0GekqyRP5c4u534imA+s+qJWVeqAApEiFIzn5+V7HZpYwjawHKZQlhYMTBEtViwtURw4qGfmXaa54ewkrMdaWZrm94F/gjwCPJkrOzZhGheZt6PpALUM1AQKxaRmaBZcqRX7Yq82W3DTDRBnGVVo2ZBpaGaXIwas8A0Dr93x8AvmYnxl/Q1aJPfVmeQBj7oL19NHoxPmBcpZqGg00YQvK1hkNRC7chFD0QiLDKorQzzwFsMwV11wt6XT1AeolLIRNeH1fc1YN7qxreo6FkniHR1b6n80qsr3ENMJmWnciYDzBoQp7DrdvouAuy0kR2wkyNHWlyvwKn/sWYRFiGUYK1dLveYvKutsBONVqisW/gnCG7mN1zG2OcrX8X5bAZMjfK7IjtfQPLnTGz+6wGciMn5TpqGSN145PfyA3Iro6BIR/SLTdBU7v3zXb8nDwXfEwV10Ib2cZ
    username: AgB/Y9FidHVG40bfFSua00blARKqspyI/pJlrS5v98XkeLqJgA9Atmj72jBCb6yTQVaUCsDNlc/lkoKKrIcQjMojrBCAC0TtK3Mz5c422aiKoBqdx3yzF//KktPHBiwPk/IH2qLnU59oNERa6DDZEVxQrS6UrE2D0OosTVlSM8vbV4Sv/wVvdYQGss8DAsZM08gkxyAxyGigjYnsVUgUdBYlHUkOdr9jbVE4S9AUnDTDPDktdVUs+fbShz0nb7UfGiHs8TNhsoCFzeMWSOHrApYXM5ITcGjNFefReFLU19RI8qp5LMtx3mZQUvFyyb5701mn8p2Jn62AiEBLnxXrkWFShHaJ+UCX5OGBJ8jgjjZKPCc6/Ax82zBtglpcCJIVtL9BdvQdTjRehespAgoFbtEGWVy+6bJ6alAiSvV+/Nt24isXvdq2VB685c+5y75D+7vprkCYm9znzmIC8M9ySEi0+OvHgdjK6NZmYL8VB9f2eTFPu/l0dx2dBTYvJrKlw9ZgXilCh3IKJ8OvKtMqGIS2BPEKEB8Z5weMR78IFE8gVcu3Dj0/u45Z3GiPq36ETccXMdqYLRKGW2dGrPm2z+I60yULqczopxTQGemrlNVWO9OkaRbe/u0UBqqV9RQ2LOMxWXddqdiv1arTXFjoSUGU6MDowcAFKeWaGF0Xi3QaPUV7CCUEjJPBkRXJmkPveDJYX4twKzE=
  template:
    metadata:
      name: git-creds
      namespace: argocd
    type: Opaque
