apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: git-creds
  namespace: argocd
spec:
  encryptedData:
    password: AgCrKBF8W0c5vD/KiP8ezg8p2kuN7lBqerTOdgkSNzyQARDWOrXhQaU8GL1z4DX25gu1V9YojMIGpToaPmgb1FS2nWHteMlhupZv4tU0tpAolzQZFmoOqxfVhRnXtU4FawoF9AFYYDRQP+XI1QiXTDrEAAN3uppBpoUlbNIQxhbMS8zQoLrVSyig8oHfvSqjyrJsfo8ed+cWYWDcSS9wQbGPay08ovejG1nimqXzzHewtuCooR20OXiO2EQ034+SYhz/a8kLMjOfHuc3gshwGEoMD0gaRSoXhohHrgh/fD9iwKvCYiVE8wpc3Cjp4lo+7CQ4VLIAJ4PwbaHUVf3wPxFq3M1aCutp+b/OrLOcbRX6ZWUUTlaYNnOELGHbqs+Te5GmbFwxt1PJFsuixFkc02QuM1eW2KmucSTaH19qBQgFT0qdx80Y9fALVMdxcb5rsxcm08jpZVt5OD7aQcceyFhhEuONOQegPuoI+lr53rP42LvswrKmVWdx590mTvq1UpY8AvlWCQyTV+1iX+uIGDF+cl7UmwVA5+v+g9+9ttFBUST8QzlLGWgfwSD5s1b5NknDcXwXsqPFBp0cMC/dHkRD0xKIqo/e5UbY+8s/IqUcmDQCGb8H5sEI2O8xxnOYAN8VuDxv++8p5ChfmgHocsI3l/VsMwIfjbiYWgmkTtqUZ2/wFpfoA9Fu/xsRm5Kmvs1C6JKr6S/IvhQO8O5OFpN0V5/hEQCtrJR5wIysPJgLRtr6ebMSXhkb
    username: AgAiKZmqfbH7c8ReJ1PjIEIhe1BIJmDSmvFJmdeRYebLfu3UtKc7R3vX4HamJSbRBKkhCIB/cG42FTI5X3zSfWyfqeq72TFudC8BlElPWLtCYAr4GBH4sBrU809DDD5OAuG3iH+nEaaIwmdoWxOiB/8zdxmcqcMzMTxT/dfFBNtjUxEyp5u8e8sUTi4tNeIAezV1ohFHUmhN/UXjY7/YkdKMRb5VWt7pqCwXGgxzrlISi7wfnI/Oh3IBcKug0ymb49FPhZt2XTgK1IxD5g5I3fjTuy2q3iskEzD02J/t0QFnUpiq5+wDpf9VjrCpIpOVUrGhqpftQpiFHBVwmZUSOuOJX7m/RlE2jYi0u/M9lT7cgLiw8DDtI4MAp0TcB7ouCQp9hWfjmDtwAB4RTXdCTR89qNX83+NOScMRVoZ3HWgTZBFizUSHNzu308d4Po8IralaGdcbKoorWG6q2FFZMZveoPTwTf+THokHL6+t4ZuJuPYRpGY7OwAVoUb4H2xFTTTh9et6cRGZfmE7qU9ycysY17i6GxLKR4xc62eVah/s1Ml6s0070a3RJopqEYV7xeZ1YxE8jbKrkul5r+8+auxU2Vwdj+/SHGbfjlIRr8FPxpmHlOnHgvzqcMuGMZ/fzbyEIPvw0vEEM1EG09gmtGIoaZvJIZvNvrxB19DsWArZvkK/DsSljLAQBZF76ykwr9dzStmx5nE=
  template:
    metadata:
      name: git-creds
      namespace: argocd
    type: Opaque
