dnsPolicy: ClusterFirstWithHostNet

nodeSelector:
  kubernetes.io/hostname: talos-worker-1

persistence:
  config:
    enabled: true
    accessMode: ReadWriteOnce
    size: 10Gi
    storageClass: local-path
  media:
    enabled: false
  cache:
    enabled: false

volumes:
  - name: nfs-media
    nfs:
      server: 10.0.0.23
      path: /serve/starr-stack/data/media

volumeMounts:
  - name: nfs-media
    mountPath: /data/media

httpRoute:
  enabled: false

service:
  type: ClusterIP
  port: 8096

strategy:
  type: Recreate

env:
  JELLYFIN_WEB_DIR:
    value: /jellyfin/wwwroot
