podPrivileges:
  hostNetwork: true

dnsPolicy: ClusterFirstWithHostNet

nodeSelector:
  kubernetes.io/hostname: talos-worker-1

persistence:
  config:
    enabled: true
    accessMode: ReadWriteOnce
    size: 10Gi
    storageClass: longhorn
  media:
    enabled: false
  cache:
    enabled: false

volumes:
  - name: nfs-media
    nfs:
      server: 10.0.0.104
      path: /mnt/serve/starr-stack/data/media
  - name: jellyfin-cache
    persistentVolumeClaim:
      claimName: jellyfin-cache

volumeMounts:
  - name: nfs-media
    mountPath: /data/media
  - name: jellyfin-cache
    mountPath: /caches

httpRoute:
  enabled: false

service:
  type: ClusterIP
  port: 8096

deploymentStrategy:
  type: Recreate
