apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metrics-server
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-3"
spec:
  project: default
  sources:
    - repoURL: https://github.com/kubernetes-sigs/metrics-server
      targetRevision: latest
      path: .
      directory:
        include: "components.yaml"
    - repoURL: https://github.com/alex1989hu/kubelet-serving-cert-approver
      targetRevision: main
      path: deploy
      directory:
        include: "standalone-install.yaml"
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
