fullnameOverride: dispatcharr

controllers:
  main:
    type: deployment
    strategy: Recreate
    pod:
      nodeSelector:
        kubernetes.io/hostname: talos-worker-1
    containers:
      main:
        image:
          repository: ghcr.io/dispatcharr/dispatcharr
          tag: latest
        env:
          TZ: Europe/Ljubljana
          DISPATCHARR_ENV: aio
          REDIS_HOST: localhost
          CELERY_BROKER_URL: redis://localhost:6379/0
          DISPATCHARR_LOG_LEVEL: info
        securityContext:
          privileged: true
        resources:
          requests:
            cpu: 200m
            memory: 768Mi
          limits:
            cpu: 1000m
            memory: 2Gi
        probes:
          liveness:
            enabled: true
            type: HTTP
            path: /
          readiness:
            enabled: true
            type: HTTP
            path: /
          startup:
            enabled: true
            type: TCP
            spec:
              failureThreshold: 30
              periodSeconds: 5

service:
  app:
    controller: main
    ports:
      http:
        port: 9191

persistence:
  dri:
    type: hostPath
    hostPath: /dev/dri
    globalMounts:
      - path: /dev/dri
  config:
    type: persistentVolumeClaim
    existingClaim: dispatcharr-config
    globalMounts:
      - path: /data

route:
  app:
    parentRefs:
      - name: traefik-gateway
        namespace: traefik
        sectionName: websecure
    hostnames:
      - dispatcharr.talos-cluster.local.obleey.com
    rules:
      - backendRefs:
          - name: dispatcharr
            port: 9191
