---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin-creds
  namespace: observability
spec:
  encryptedData:
    admin-password: AgC9jULWOdbglEM04jCXvQ++J5cVkXjlm+5FOT36BcyhVtte+z4o9X72JXyTdqCH77bACsubB5tGvL4B54OpP2UF5y6M5/+IZqmFlLRHWeg+ShEE1Ud+xv8ExC8kvNPwGi+SdfbceoyiWsi5wSDuoqnudFqqmLt0jUd9uKJb+r0p4KuJWbiRC002oEBAmV54Q7/8GRNgdeuUoRRtf6YpEWEs24dCpy2YMzJ1jjAlSwlVPgT85CDVo3+ICVUH+7PgJrZgX9x+CQV+gDcsQIugdr6qCoBkMTtJkfkGyNTSO4R51PjRMJMOgAccq5iC+lHGX2U8c3Nsg28D/6UpAgr3I8W+Oc2TEQU8YZ+ez/V0gl0ZxkQY789R4SykjbD1Brz8ODIeGTG/dFb4qRSVJPdIAGpkpSwfX5A7+hJwtP+IcUzxQahV9FBfRA2e5Z6N7SJNaJtPjmXG9F50RS9VnwVHDNjHtJAoZ8PAFlP2UH1SwfLMmlDUbqqOSgYaXLzPps+JrSsQTWnai1Zo99oBjtfIjhpowYy83jKKK58vl5mAowd7qLr18FnXCAHuxpUgGV6BpoH4Za0pLaheZo8Ut8SWVmAjPeQSSufmZQzBsiUQj6TfBWeUMfIrP7TvRQaLWKG58Ja0GCkNc4FHf43ct8pTQE77NO5Jf51ikbhxIvouyFPphzmKfqaEcx9a/OuaLOivXiRhgHIn1N23KOZp5VuTueWCiQ8=
    admin-user: AgBiQ6ftNs4eqwbejIzRY67uO9WPqyz7hXuGIlYMSi3MyseYXqvBcrkIhOF1oMar6wBZ89ZyvGW2lH8wGKsXPCn5dM6bFT2eELGaJsuYlZ2mamGEWsvG8kaAv3kYYhorxcsXJqRu/up968Uvyd8MGfTuchgkP2ee/+/QtkpSxtCcxJ6dnqCc/9I88X60oP+eKqN036GslsFHpYGCY0In8a6Yg3mlpvFciJVxmjG2i1dE4M9reowT/KEXbug0qMaGARPQP/E0iDOzTgg79087dbepU9qToZRvj/QaSIATXWNyuWNT/DVSA6JOQ9PsFssAzfzRB7XnNmDyypA49cZ5IdbXY/NCoKNnhfNBXW7tIG+QcndQq2tPX+UbIq03wZRUvVVjjnUzI7PVg31/s4CL3LoYs3/rN9XLnn/tsTAW7n7oOy9gY+S3ZU3wjd2+Rem79vaWT8eQsxYQ7wp4hCrO2+IrjCgyLxMLb0UnJiLc2Gpa3vqkFgIx1A2sTJMXNx8+hE2p2Usx/0vLs7c0GqHoH8T9frVKm92vgpCNpSEotSif/q0GLWtCzO7YRdNiT5gJ1+pykdHuv2g6i5F0dSi6jnwFNsL/r7Xx3Qc7OEER/Jio3w79u0K33AdBDAgnmmpJe4oS3OrGi3kn+pOFqCLK2bzfdkJuGFvB0MUq44lhu9+kGZm1tpu5qTBy6c7yfc3jTaD7HYBKBKk=
  template:
    metadata:
      name: grafana-admin-creds
      namespace: observability
