apiVersion: apps/v1
kind: Deployment
metadata:
  name: unpackerr
  namespace: servarr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: unpackerr
  template:
    metadata:
      labels:
        app: unpackerr
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
      containers:
        - name: unpackerr
          image: golift/unpackerr
          envFrom:
            - configMapRef:
                name: unpackerr-config
          env:
            - name: UN_SONARR_0_API_KEY
              valueFrom:
                secretKeyRef:
                  name: api-tokens-sealedsecret
                  key: sonarr-api-key
            - name: UN_RADARR_0_API_KEY
              valueFrom:
                secretKeyRef:
                  name: api-tokens-sealedsecret
                  key: radarr-api-key
          volumeMounts:
            - name: torrents
              mountPath: /data/torrents
      volumes:
        - name: torrents
          nfs:
            server: 10.0.0.23
            path: /serve/starr-stack/data/torrents
