fullnameOverride: unpackerr

controllers:
  main:
    type: deployment
    strategy: Recreate
    pod:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
    containers:
      main:
        image:
          repository: golift/unpackerr
          tag: 0.15.2
        envFrom:
          - configMapRef:
              name: unpackerr-config
        env:
          UN_SONARR_0_API_KEY:
            valueFrom:
              secretKeyRef:
                name: api-tokens-sealedsecret
                key: sonarr-api-key
          UN_RADARR_0_API_KEY:
            valueFrom:
              secretKeyRef:
                name: api-tokens-sealedsecret
                key: radarr-api-key
        resources:
          requests:
            cpu: 50m
            memory: 128Mi
          limits:
            cpu: 250m
            memory: 256Mi

persistence:
  torrents:
    type: nfs
    server: 10.0.0.104
    path: /mnt/serve/starr-stack/data/torrents
    globalMounts:
      - path: /data/torrents

configMaps:
  config:
    forceRename: unpackerr-config
    data:
      TZ: Europe/Ljubljana
      UN_LOG_FILE: /data/torrents/unpackerr.log
      UN_SONARR_0_URL: http://sonarr.servarr.svc.cluster.local:8989
      UN_SONARR_0_PATHS_0: /data/torrents
      UN_RADARR_0_URL: http://radarr.servarr.svc.cluster.local:7878
      UN_RADARR_0_PATHS_0: /data/torrents
      UN_PARALLEL: "1"
      UN_FILE_MODE: "0644"
      UN_DIR_MODE: "0755"
