fullnameOverride: clonarr

controllers:
  main:
    type: deployment
    strategy: Recreate
    containers:
      main:
        image:
          repository: ghcr.io/prophetse7en/clonarr
          tag: v3.4.0
        env:
          TZ: Europe/Ljubljana
        resources:
          requests:
            cpu: 50m
            memory: 128Mi
          limits:
            cpu: 250m
            memory: 256Mi
        probes:
          liveness:
            enabled: true
          readiness:
            enabled: true
          startup:
            enabled: true
            spec:
              failureThreshold: 30
              periodSeconds: 5

service:
  app:
    controller: main
    ports:
      http:
        port: 6060

persistence:
  config:
    type: persistentVolumeClaim
    existingClaim: clonarr-config
    globalMounts:
      - path: /config

route:
  app:
    parentRefs:
      - name: traefik-gateway
        namespace: traefik
        sectionName: websecure
    hostnames:
      - clonarr.talos-cluster.local.obleey.com
    rules:
      - filters:
          - type: ExtensionRef
            extensionRef:
              group: traefik.io
              kind: Middleware
              name: authelia-forward-auth
        backendRefs:
          - name: clonarr
            port: 6060
