apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - sealed-secrets/app.yaml
  - cilium/app.yaml
  - cert-manager/app.yaml
  - traefik/app.yaml
  - argocd/app.yaml
  - metrics-server/app.yaml
  - storageclasses/app.yaml
