fullnameOverride: autopulse

controllers:
  main:
    type: deployment
    strategy: Recreate
    containers:
      main:
        image:
          repository: ghcr.io/dan-online/autopulse
          tag: latest-sqlite@sha256:eeba968613d6c870c3d1a6bd17ff7c33192b866999a38acbb3904d93be252e40
        env:
          TZ: Europe/Ljubljana
          AUTOPULSE__AUTH__USERNAME:
            valueFrom:
              secretKeyRef:
                name: autopulse-secret
                key: AUTOPULSE__AUTH__USERNAME
          AUTOPULSE__AUTH__PASSWORD:
            valueFrom:
              secretKeyRef:
                name: autopulse-secret
                key: AUTOPULSE__AUTH__PASSWORD
          AUTOPULSE__TARGETS__PLEX__TOKEN:
            valueFrom:
              secretKeyRef:
                name: autopulse-secret
                key: PLEX_TOKEN
          AUTOPULSE__TARGETS__JELLYFIN__TOKEN:
            valueFrom:
              secretKeyRef:
                name: autopulse-secret
                key: JELLYFIN_TOKEN
        resources:
          requests:
            cpu: 50m
            memory: 128Mi
          limits:
            cpu: 250m
            memory: 256Mi
        probes:
          liveness:
            enabled: true
          readiness:
            enabled: true
          startup:
            enabled: true
            spec:
              failureThreshold: 30
              periodSeconds: 5

service:
  app:
    controller: main
    ports:
      http:
        port: 2875

persistence:
  config:
    type: persistentVolumeClaim
    existingClaim: autopulse-config
    globalMounts:
      - path: /config
  autopulse-config:
    type: configMap
    name: autopulse-config
    globalMounts:
      - path: /app/config.yaml
        subPath: config.yaml
        readOnly: true
  data:
    type: nfs
    server: 10.0.0.104
    path: /mnt/serve/starr-stack/data
    globalMounts:
      - path: /data

configMaps:
  config:
    forceRename: autopulse-config
    data:
      config.yaml: |
        app:
          hostname: 0.0.0.0
          port: 2875
          database_url: "sqlite:///config/autopulse.db"
          log_level: info

        opts:
          check_path: false
          max_retries: 5
          cleanup_days: 10

        triggers:
          sonarr:
            type: sonarr
          radarr:
            type: radarr
          bazarr:
            type: bazarr

        targets:
          plex:
            type: plex
            url: "http://10.0.0.161:32400"
            refresh: true
            analyze: false
            libraries:
              - "1"
              - "2"

          jellyfin:
            type: jellyfin
            url: "http://10.0.0.161:8096"

