fullnameOverride: byparr

controllers:
  main:
    type: deployment
    containers:
      main:
        image:
          repository: ghcr.io/thephaseless/byparr
          tag: latest@sha256:b44c612ef598e593346852a9a9ce92b8789e9ac8080544bdd38e125b99a2ee69
        resources:
          requests:
            cpu: 50m
            memory: 128Mi
          limits:
            cpu: 250m
            memory: 512Mi
        probes:
          liveness:
            enabled: true
          readiness:
            enabled: true
          startup:
            enabled: true
            spec:
              failureThreshold: 30
              periodSeconds: 5

service:
  app:
    controller: main
    ports:
      http:
        port: 8191
