fullnameOverride: byparr

controllers:
  main:
    type: deployment
    containers:
      main:
        image:
          repository: ghcr.io/thephaseless/byparr
          tag: latest@sha256:01a46a2865d9a6db5eb8ead04ec0dd33b8fbe233e8565ae70b50d4cc0af4cfb0
        resources:
          requests:
            cpu: 50m
            memory: 128Mi
          limits:
            cpu: 250m
            memory: 256Mi

service:
  app:
    controller: main
    ports:
      http:
        port: 8191
