apiVersion: apps/v1
kind: Deployment
metadata:
  name: byparr
  namespace: servarr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: byparr
  template:
    metadata:
      labels:
        app: byparr
    spec:
      containers:
        - name: byparr
          image: ghcr.io/thephaseless/byparr@sha256:c3eb36925057fd304a95e300626063f9bad3a1b7cbfced7f4e2a3a819905ce83
