apiVersion: apps/v1
kind: Deployment
metadata:
  name: byparr
  namespace: servarr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: byparr
  template:
    metadata:
      labels:
        app: byparr
    spec:
      containers:
        - name: byparr
          image: ghcr.io/thephaseless/byparr:v2.1.0
