apiVersion: apps/v1
kind: Deployment
metadata:
  name: byparr
  namespace: servarr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: byparr
  template:
    metadata:
      labels:
        app: byparr
    spec:
      containers:
        - name: byparr
          image: ghcr.io/thephaseless/byparr:latest@sha256:01a46a2865d9a6db5eb8ead04ec0dd33b8fbe233e8565ae70b50d4cc0af4cfb0
