services:
  alloy:
    image: grafana/alloy:latest
    container_name: alloy
    restart: unless-stopped
    pid: host
    network_mode: host
    user: root
    devices:
      - /dev/kmsg
    volumes:
      - ./alloy.conf:/etc/alloy/config.alloy:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /sys:/sys:ro
      - /:/rootfs:ro,rslave
      - /var/lib/docker:/var/lib/docker:ro
      - /dev/disk:/dev/disk:ro
      - /var/log:/var/log:ro
      - ./data:/var/lib/alloy/data
    command:
      - run
      - /etc/alloy/config.alloy
      - --server.http.listen-addr=0.0.0.0:12345
      - --storage.path=/var/lib/alloy/data
