---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: kps-grafana
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgC0QrJSok3jFukQVGUSHD9qtZfsgXLqEhtFqAmE3/uMM+g8tzyne4DJl5raonoB/iIe5zN0ZMNZHrCo0rWFCt+TA6glmXL6k0YIGgtVl6yZNEm02SEFOkmMJ0noyOyAVJwjXWZlGCSaRoyjXki2vzuKBiayb3fJIhXI+EG06edSjz7EsVY6N1t3/+yYzD8gti3UHNSM/bCKLstO2MlgZCD6+/QxgHN6zRrzW+OaC3bkLGNZpf2TrWajf6XKmcRUSt6FAr3EP/L3OD/AFzVly6q5FBi6tQ8wgo+sCiMlK/kmg+YSo9rqdqm9ur193srtmZoriCMFJMCpj2ncYauGHfMcq7qPRjvy6H8VbVdYajN/c4rA0mhKfQ4meq7CrMX5zgXIZ0J+UknQbFN8uVWJfeXkiPm8/zZJFRzNOQJ5LN4ssUiH+f4vtD1SQuWV7aAeWCmA9+FhRZ8OvRfC13HdKNemH0paTmb32ehJBpl7Kh6J1d28zuWXEXbTFHVmNqo6NkrBJ5efExPotoWiwfdDPMynABFw5ij7LfLbCaLGNpXH73/VFfVZ+f1EWghHMV4UlDFYOKa6osdOB/9LT5OxS9D6E3UjewbbcigfXN73MkBkEhIONv8wFN2qwT3qpwNpNnye3RxtqrKyhnYrQcGtzhb5QzXfBY6VvM9Hk47AOJMJdvHPWhdCfQRLgCr7P76SaAwCu4xh2BYZpPKPjsKD
    admin-user: AgBB9s96u8qPHWv7A0ijHnM4dwxjD3OxqXlVGFqq6lwUKTR5YL2aq0xUASZpx9mwBGQbfSIRcaOxUH7+xZncwcfqTbPkPoEmk0ePgIo2rzVn+xLyL76LJimDQGTSpcTUa/jWorw/7PSj3v/AMQ7MI9dLbkGbWxXluxHt1axp61rSmVsCCR/xqSHeeo7c5++4/rIApKuqmHKQ5sp2p3z6N4UDSC39FcSpq5lznkCA7SACo0c9rFgiCi7IE5Cmz5uQl7nT2vKVAKKNzZGDVa8BwwP4wm2arGjpVJY3hF/FFgRIGjV0NVUJ5UnLgLlbuLZEJlo9Vh/1ZpSwgwedZVP+hpMyC0os/IPR7eKWvUfHQyxPCUdIz7hC9Xait9oAPMBopQwCI4sn9X92gTmwPbRk7x4KwCCPm/pSQzxOeateJFxPis0XBYKZy6z/0qQHosMGur9ONctm4YAIpVTWLFgHyU71NAx8K5wCiDbzArQD5l+qURtNRBYKrQwSSUNMiIXwElWVhlSnSHcbzW+0Mx3pYhYseUxh3pLIQfA6LwZrOM1splM+fFE24z9vwo5cZ0a5YxLM9bWNUJs3Qy2QqTedaP7ude8uEpzgYvZNYYrXao/TiWYY1fDZKCDs7Ey2AbVoHkSm0kt9/iezcIDU2wyqUXk8WAHih0iqaZ0+dCKCBf6tZg0FMV3NcBR1XvmEqisDN3lAKFedXQ4=
  template:
    metadata:
      name: kps-grafana
      namespace: monitoring
