---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-slack-token
  namespace: monitoring
spec:
  encryptedData:
    token: AgAzT185X1dmyBFyV821e/xFa/dtWB1C+1qFLo1SfFYriXWNQERQnlDrDcjuvLtJP6XwD9BpIg9+msKIZ1fL7PfMULo534wNEFcnOl/upPDYEHoV7OpmRRZG0NvxjyUIEA7TygbtRyUe2eSHJrOMmDca7FOUV4Ur38rcFn7eVHe4VK9JzvTwj1dgzmKwxZ7FxTS3nndS+Fy/sNi1XjfozGShzgqNwe3PKv0/RJL2Qe/h0QMtNCg/AkbDcnERCB3WvSRsyYQrzMyxMTMEZq+qRwCSgFGGDmVKzNENuodRT/L0Ig4kZjY5jMyQuGOdndU0fCMJLM+4sf1OKDwsySEDBCmgU9+Rx5v8r6qAbwa+YSjrubIObZ4vRt6+re2boD4H0Pr35Zbm/Mi6ORCwVNNXAeCuIOdN0AK4ym86fwz2fDt9JaimMIxCxhEoP09zNIKVd7MMNVdAGb//fHgYaITQcdBHfzzmCMMlhFTUCc1Dz8ygxtEfvEZ4glpHW+609SsMFAX9Yc9eHQz1vcw55NPMmsolznuOWCScYKdOYTA5SPiewJxZj6s4Viai16EUZs78VzaMPtv8jsMCiD2q6LCZGjz32fzdDJ9INXWBvImlH2b9BxJj9cUsPAjPBmtyN24wlApv3diknesuUeDwUddyvbbthpV+Wt3ssKszXLH80fOK2XMR6YHu6ojlPbzTsoe5seNlbpX2kGJKsdv2xM68PEN9KsNMPZ6jbRMvBkBszfWqVDh6BMjiBgfHgStsAX6o6QtezY+9r1/yXgnE9g==
  template:
    metadata:
      name: grafana-slack-token
      namespace: monitoring
