---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-authelia-oauth
  namespace: monitoring
spec:
  encryptedData:
    client_id: AgBU7SwiKCGbGGum1glBdWTpzM4ngzu2QFfVzYIsndADrPcGKboVyoILwyjKM+DXwcWbTsxzZr0naEdT6yzoKlEQZ0YfHeqJ8tDDMNCHGY+sMRMGYH0e5LsXhPy9/5dpaORZJljxGXa2cUfQGkQDudGxbnlUKq5R9jd3I+VcWbet73H3CaliJ5qbQ+tz8NJ+NBUFOLQjBh29BLK3NeHCRfX8ELCleuM3+oqRvGxFGK40F36osbnMvJSllsD2y214uSmOpJJ64c8jxMkYyNn1/ztPiEBJKJAWntIDt4wJGezIokBZaNHXIvFehXO+csj7pYa4XJSqAatwOJGxGh/5AWSZkouScSzJLEWmOGi39ZI7K4mIIHFCj72Xghpq01eoaXvqRQcTQ0EscjOq3TlFLroz1gNwEKu215jCis5k6X1zEQt/BeCepS4Xm4wHMS0bw3gr9ViCQC/WEU05y4OiDthnNhMCdjg8q2RC8YOjtraY8SJ8Y8CXNN0UmzD5I0PbQCn/fJ4gDW5q/QCp7aolp/XY6UEfH9tvxVRIrj4P/7DVv0MEyQIUNvazryukxidLUgKOB4WzVMLLTbEHNK5AStof9HCaE+xEL2NneJjBIj6c7HZKgmp4YhKyKG3NqkPLLYFuQXQiQNA25mNzUWKljpoSKDt8dttmyBeEmI9uObjuwK/icesRc/hCSITvOQhZM4ecRtWjX+9j
    client_secret: AgAjvv2S+Ygq+GWrUheJnyDP67iXfE5JKENJhyKXnjip6FJ6fNc0WJtXQ57zKAapt9lea9WbWRtJahcEfAOyYiexn9/lj26leQjVFix2FiOv5U/6xt7eVw/wLB8j839imToFb060qRZiUGDAXlxGiQqPlzea+dkbWaC2w9e2XP+0iQiDW1VmUWdHB2qY845q3JmkphH9TmwmiD7nP7iMhcKvxod7bAfESNQLZGdXGvwoyl7Bla52knF/w5oc1wvkII/nwsbAdG2LVxrzxXnys+f7IphKHTiREnvm8OjsgUPriRyQWPff3npW1T2eHQfbDt5ctJHUYnD/QbG8YYdxgZ6vCFY24kwpbn1QzrAVTX3Zt8SzavdxrHDH3OdXRVDtDfy0O3FVOAOzt2WC/Nwb9HUxT5+0az1KZYXidhlFZ97VV5HkwA6gqbmrgyYqAOcRF/2woeOf96I4LJE5E9zN1+54xaSnEhZWJ8rqdPnMcEjbaBq0k6DynvKjC2PbD5w4xENVIdEe0/srnzVOjXer4tZSpjkw+RBwH0kWo88CJ4bUkh01GgI16JfKMv71eZHwuocJj94/hkbnxmKe9W03+YeGrMeXdzWV8SAd0fpCxmed4q7xm5Wmv3NvSbnMASS9hMj2tr8AacOjN9OlULOVd3SFsB+3IZjPweWPIf4LRKrfPPfDo4aei56Yg/SzWwbIQGVKe6Eik8rBlL3kLJDLBGOWnkpALmKKmbNel5fFIX+1c4yGkmVwHJWPcjO4ShdxW45WhRBkzyEmeJKgxNOxzDUR
  template:
    metadata:
      name: grafana-authelia-oauth
      namespace: monitoring
