---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: prometheus-basic-auth
  namespace: monitoring
spec:
  encryptedData:
    users: AgBS9x8zNyT8Oe4f/eY4fk8mFs2TojHTQbeHrIQKLC31MnXXF6Fo9X+UaehL/hEkbUJTZ+oIGG85iZMovKCFsTiCzWlvSNYvCZ4yVAftrCtQ/i0KDnMF302qifH8hsQj+W4UoSnj0sh+AbUeaiuMXFtihKZPZ6JX8LSjXUnq0GvPcEQHKjnx1nTN5pRo5/EmjC5QUhngyjycI6B/TuOZKlliofKHdZitJHjvy4d1Ye4r9VTdCWDkos1o4adWaWKYPl3M/Oay+dWjv2KeOhzytjPR450TzgW+6a0iLcIy6E5CgW9xegOHcWLTwplOOo3MVvY17bo/dkfxaGtGFvJxTaUyEqX7qzljhbRwMt0UYjP4fYBebh2TamAZKayHaia84rwMGiuL2F/SLEmBBuo5nmWlN+L6KjuORq+f+bSpdtIPzbMLYShtRUZ1evmEN0SrbhNncaWmvQoJdN7UHxtyLROlBR+HB5LoZSvb5XqL8fEMh+97HL7dB7pIAMOFtPq0+x0xF5nnFBqL5zHQTJLlhPi+r6Mj+Xi/Moco/YKLg8joNsbUxNt8Y+HThhSs7Owm4Pd6P4XvXsqROK8GLu1hIGTzt6M4Vez6PnDcV06F+J90aBi0tqUFZhUIXFuo9M8XwmhkiUOVjR5FZHxtOIx5fjyEkyQcKySt2l/KXWMjBhU/wH0vrxw5BTDOVwasKN2hAl59cIQrxIHEm16fEwHqEULBe30s8xYA/DVuNnXIAJF3uABz0ZdJRn4a1CVG1wn5fM10gZytUX81cacbqX+c9CwEy1CJ
  template:
    metadata:
      name: prometheus-basic-auth
      namespace: monitoring
