---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: prometheus-basic-auth
  namespace: monitoring
spec:
  encryptedData:
    users: AgBwOw3IhmrRDw01MFSgN32/CgB1VCEyNUP1QK3R6mXbJ93OFbwkCdBbZ0StPodCPQXMYH6me9i+eTBfh35fgqiJ/9yjX/mr4NZ87Y8OCE/3BDPE1krJOKO4bvyqly0Uvl3hGbYIsQuL1Ul+Xgn2R/BH9f/crXA32+iHYPJR8gJXbYdMFeSaDRiJmYKhjIvNO+G2FseGKrN4zw+zhakGjvmklj+mvpl66Rqb8h5cYrVC6ZbWopdSE8gpYLt4QCFHMHgmBiLuWP+llLaCqaHIHXlJWfaaPwAVYOh3ilBqZLIcH0Hmfw7PNUxI9BtZ6r4iX1AP7c3HJbREqMKFuaym8bCO1jteWxWH7lR7r749L2slGNHFYWqlzo6ErBRCka8IsdKAzPrNrjJWCoI7JoiRUQkDXftpLScQ9f4gv2GOzTGMXhkbXjh0Akmpfs+MMOQmcvwIcE80OBns3IMUPAMZwFU7lvVFs3Rz9BLYv4ruQJFCCnyf07DbimGeq2NTnLl5RPDVwEe79MlRXl1FH5v/l4kPDWQOnbJ4lqY/FhUwj8pjUoxc5Pf78VlBQTxGm9vzMOiRh2ud/UTbfqx89AO/GDoWw0R02vJopaGrGVQ43J7rYRq82mUnaW4uTJKJ4fvPqM/yeQb0ysn9DPPoi+7f9Hv4wTetbclNwiZQqMj9Z2Rml/WCPddLgJJAAodj3HYPU4SZv8DBKYYVi97IZXpAQhMUkI0uthFSZ/d+9SgYI0qxvXeIWzsV7JhPGc3ZoY+SldNscm50xwzNp1EVA25du/SlMV0=
  template:
    metadata:
      name: prometheus-basic-auth
      namespace: monitoring
