fullnameOverride: radarr

controllers:
  main:
    type: deployment
    strategy: Recreate
    containers:
      main:
        image:
          repository: lscr.io/linuxserver/radarr
          tag: 6.3.0.10514-ls311
        env:
          PUID: "1000"
          PGID: "1000"
          TZ: Europe/Ljubljana
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            cpu: 500m
            memory: 512Mi
        probes:
          liveness:
            enabled: true
            type: HTTP
            path: /
          readiness:
            enabled: true
            type: HTTP
            path: /
          startup:
            enabled: true
            type: TCP
            spec:
              failureThreshold: 30
              periodSeconds: 5

service:
  app:
    controller: main
    ports:
      http:
        port: 7878

persistence:
  config:
    type: persistentVolumeClaim
    existingClaim: radarr-config
    globalMounts:
      - path: /config
  data:
    type: nfs
    server: 10.0.0.104
    path: /mnt/serve/starr-stack/data
    globalMounts:
      - path: /data

route:
  app:
    parentRefs:
      - name: traefik-gateway
        namespace: traefik
        sectionName: websecure
    hostnames:
      - radarr.talos-cluster.local.obleey.com
    rules:
      - filters:
          - type: ExtensionRef
            extensionRef:
              group: traefik.io
              kind: Middleware
              name: authelia-forward-auth
        backendRefs:
          - name: radarr
            port: 7878
