---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: homepage-secrets
  namespace: servarr
spec:
  encryptedData:
    HOMEPAGE_VAR_JELLYFIN_API_KEY: ""
    HOMEPAGE_VAR_PLEX_TOKEN: ""
    HOMEPAGE_VAR_PROWLARR_API_KEY: ""
    HOMEPAGE_VAR_QBITTORRENT_PASSWORD: ""
    HOMEPAGE_VAR_QBITTORRENT_USERNAME: ""
    HOMEPAGE_VAR_RADARR_API_KEY: ""
    HOMEPAGE_VAR_SONARR_API_KEY: ""
    HOMEPAGE_VAR_BAZARR_API_KEY: ""
    HOMEPAGE_VAR_ARGOCD_TOKEN: ""
  template:
    metadata:
      name: homepage-secrets
      namespace: servarr
    type: Opaque
