---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: homepage-observability-secrets
  namespace: servarr
spec:
  encryptedData:
    HOMEPAGE_VAR_GRAFANA_PASSWORD: AgA9FvrLKb3lwyzF1J1iBZgdxpt+VQPz2HNrT6Gkg+y1qJ2k7osslUbbjUQhX6DxTandt758o2QoP9gQG9FwRgBeMNxRXQhlhN8hlz00IEOdImzj9yu4Xp8O+FzIMCda81bRmqF58F9OObsFeZkYYDZDb61AD5zadvDLtSI/Z1AzDFIYZ/O54zGHFOS5W3MEDWDGWpkrBUPRh9Yq1y0K8ZTeuH5OXYhFWFU/u6He/f9iQaBufSJ9Iev0c9s0QHy8BM5MrHvEGg6Ge2qA1R5pF1P443ZPOn+9IWh34rv8p9ol3dTbZtAeu3qISCRmFZZ7F2aHUV3fefdQhKwPDvRaDzXb+llUUjJ+kd5cPp7KhovFEZaTCLscVNIDGR/NCap1qZITWAEsKiWRnHWXdFr6lAu85Fl3nn77U+AOghK6ChLnSE7Z0T+IrCywltrd1b+RXwKrCVl7e8JEBZLMFU4S1dGPaSUdI/fXiBz7uJX1Ee2JPb+AClBjpT+uktYAVRMfovygi7Rk6MS2n3EfKqZkXG52JZQGwaKb4xyHcTdq5phff6s3nr/sTLNcxoSB2Wq+RNjWIWw7NLSpAeFfIe1zqzZHMZGp3kLX+VAmdfmdKNUT87v//wrE+J6B6+LXhGMpbxYnbAxH+5OpyDUqYyJLQfSlh6LW0PneR6U/89lZWtyOcjolXGmG9A4JvqtjM5/0IRcna6jy0+m3T5VOQ8s1by1+pIo=
    HOMEPAGE_VAR_GRAFANA_USERNAME: AgAQ8uQaVEsqnIQxL011L8tnXmTn1io/GxyW7tXRM2uUxdJCoEXss8wtC3PX+XWTkVP+j9enX9zKMscTUCSNi80Ns2oaabU6PPxNGMGwkkqepyMZ7aEsa198ogJLCn5QavDO55nbLrL393cSn1upIrvo6gobpBd+XD898xhws0ypr5z8AyEOffdodnnAV6hAIUzz6h6O8LDH2mtpJKTF9vP61IDNveJVzzuC4qOE35ZY7VoPq3IGeElQxVVPwySV09ztW19sJ5auLA8J91cHjJFPMtBPNbIfEj6SbD/Cw/aTYQ9Z/1aj1CTZiRy/MBvq+WYy0z3BuMYEQWNGs2ObPjIqw8gU3aeK4gOGM4pi5CNWyglNtHZv5lOaPjgiBQ0P7+RN9xxl0WcgmLiBpMkval2kLdfL5RQJvX4WHbM83EH/PMPmcopHIyB8OSAdIcUDDEj66oqKvVq/r6jo/nOO9kQ81Yj4j5VqN8iHA/5/C98jfLSBKWuCishPQNTvObBD8DonaXeRs+LSrJQcFYwSHHoPBN6PGL1tJJqwS0XkkHx69MfFgbgzlCpF4GkVt+UctyhquU1aQwO5VOs/ejY1I3xPkr++BgnbXk/t6r2tUxe15xb0N/FK4cEkNbr3YNx9RjyoegLZZAEazceu9pHPtxQCJm9sUJDJFKOT8ybao1jMkqtKf/kZ2WZfGsMWmO0bBeMWMU+rScY=
  template:
    metadata:
      name: homepage-observability-secrets
      namespace: servarr
