apiVersion: apps/v1
kind: Deployment
metadata:
  name: seerr
  namespace: servarr
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: seerr
  template:
    metadata:
      labels:
        app: seerr
    spec:
      securityContext:
        fsGroup: 1000
        runAsUser: 1000
        runAsGroup: 1000
      containers:
        - name: seerr
          image: ghcr.io/seerr-team/seerr:v3.1.1
          env:
            - name: TZ
              value: Europe/Ljubljana
          ports:
            - containerPort: 5055
          volumeMounts:
            - name: config
              mountPath: /app/config
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: seerr-config
