fullnameOverride: seerr

controllers:
  main:
    type: deployment
    strategy: Recreate
    pod:
      securityContext:
        fsGroup: 1000
        runAsUser: 1000
        runAsGroup: 1000
    containers:
      main:
        image:
          repository: ghcr.io/seerr-team/seerr
          tag: v3.3.0
        env:
          TZ: Europe/Ljubljana
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            cpu: 500m
            memory: 512Mi

service:
  app:
    controller: main
    ports:
      http:
        port: 5055

persistence:
  config:
    type: persistentVolumeClaim
    existingClaim: seerr-config
    globalMounts:
      - path: /app/config

route:
  app:
    parentRefs:
      - name: traefik-gateway
        namespace: traefik
        sectionName: websecure
    hostnames:
      - seerr.talos-cluster.local.obleey.com
    rules:
      - filters:
          - type: ExtensionRef
            extensionRef:
              group: traefik.io
              kind: Middleware
              name: authelia-forward-auth
        backendRefs:
          - name: seerr
            port: 5055
