---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: netbird-mgmt-api-key
  namespace: netbird
spec:
  encryptedData:
    NB_API_KEY: AgDBwyMUpQcRfi41YADJknIFxUCx1O1gkncY3a5Wugjk/YdaqK2l7wWMLTEP2OH805WUjEi7e+ztQTYRqSmiU/G9GX8bg73OWUv/FkUbCi+1PhpFbfe5T3m3HmnJvxcohRY84V4mVFtzqEaTE3vGDDPFVeqNgvUjhrUyg/YZp82dmuYG3QwK/jD1f8fWjlTjVOYbbMSPLpsMxSpSHDSVhTNysx+pZ/HyMWcITNWZNrWgm8XNjo67f/S/leJ8ynsfCCrH6DJaEfZbj744RtsqbLo4d/dwvtzttOFk+8h9DDv18GZj5Q54fhG39ueb1YI0tKt21NV8ueYcmzmVVTWFIfybig7XR5ahgB7q8Zivv1MYSP3+nl/GXgJatFugw0gb0idkfNC19pExQIuzNMBo2W6wVfEy5HhL2GTpnUMIM5EvCiOuNoazWZU17/sCtSF98ktpthkrbknkxi4Cwh4VTTLIfpHHy/orbxgenmjRydbs344/Tyu3Dq2hCNRPH+Bn3HRENjCOqYDfl8CGkBU/Uzb6V3aduLjHpFgxSTwrI79fh+H1uo9TeL/uZbDf4EC2Qc2NQjM0Lwr7PKTeR2z7/WaVtV9Oiin1uq5osDbzrJiftQnJg5X//+J7BXqVdBQ26P52jnrF+E8iDt89wOFu0uzNK8bqJW6FvjnEpSTN+htOTXNcZRgDqZKdk5rGigtEPWEwjXaHW/yI63q7+rnjhBnz4/e3DIB4rJuBIj/WgusveyyVVF8IOpkp
  template:
    metadata:
      name: netbird-mgmt-api-key
      namespace: netbird
