---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: authelia-users
  namespace: authelia
spec:
  encryptedData:
    users_database.yml: AgCPmHsob1vZRuCtBRe18FJF5SdRhXRz6FKqaKRn0jQgF2HoeuH02KA8uCnTALaBZpuv3Lw4MRe9SzJT7laQiK/uRF31RHvMmVvstM3NerwSZsHSIRRsvIVEF2EupvFft02oHagnnO3sRSoFKrt+F3QrA7K7aGgUifWqUxhP7QLhskoz94mXEp5B9NeRxCz+5vnuS1Pvg1Jvh5StF+EK+Bdp8QziyAA4w8/4XgJXLZ56HAtlf1bdHOvtD4Vw/jv9FW0kfiL5Wuw7QHdaICo7IvcgVN7l8DXOmF5AoGLodZDZyNuJ7yWkUx5L9Xr3qnyp89BVc3hd+hpRZVe+OkGvGkuPu49mGSDgZsEkdlbqJP3RqPVnI6RWDhYUzQhOFoi07xgFMrMa+iHHsqTrAXGAhQ3krm4t7Ls1A0PQszISx0t7ff+HiGOUNhGixmhXLc1v+1+bhZ+9ZL2HonfkPy1ywi1S5cwQNhxsY2nEusRqzLvyhtPOt0B7Jp2AyRrdne4fFK5aft1UzpzBRDU7bMQb/lY2Y9JG37h8JwoZjbeXgBE0dZau9YR7gryxeBpUnguOmc2K/Tt/7iuGWm1EBYoCl7b8fNPA2CjlZp7MQWNPEN7PDDvsd5HusgUU1vSCMtaFTthuoakbSEpl97jqVoaFPBrl0f4FF0gMRFJnRQ8bX7ygUCZxk1XPTnbutFJBlOC2WArz1THAPpV9IcKfp8tkoJzCg7CisXtVpRaOwThVhhn3rq95wwXK4lrs60GCPyMmHe4JLS4nUMsRVaNkkiEHgMdbFQnHcl7RxAEmkDnP4CNjlsEB5IzYfFzGKeQ6ddV4JkPuL9zmCYEp0t26+5So2oUpCkdUVWxZrHBT6cRKS0cuDVtj11kr+zn9zE0cumDXkH0cp+WioMuojqhO2Q2xFrsCAlUutvxgCA0kWeR+ipnE05NOBFGccPEIJkp+hpiwksyf+wq4iKXYlXYTYQ+OIWpL3ibAVTR+j7dGi/xKNLC/3BIk8jE2LSMbqDAwocc+nu0TgaSM4T6sMWDvqhTWBVE=
  template:
    metadata:
      name: authelia-users
      namespace: authelia
