---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: authelia-users
  namespace: authelia
spec:
  encryptedData:
    users_database.yml: AgAvOfbtT8yKYfhFNg23cGItboCRxB9A7FfhqtZ+e0m+A5acyK+YK9KEdq4FMcIOI+BO0xQHWCLLlF7tCkN+N0YvdZ6l1K/64a6gYMrDr17lrVa78X8YZpeKuIKV4SWEPjpQTNPuRxtogqmIIIxH82mWdZq1j6fyWuFHl18BrmpIucW+k/hL4i43Yac424Oir9JWLYDp0wwNKlwUs1+cup76CHT9dYvbvDYvm8CG/ywiby20RSyk3uS6lCrktHPaBlu9sLTSu0qWXtBD5wTkiZiZVlXwhXQivQTQ6uKWBRspsD8oFP7yx87Y5bzK7OTmgRR+451AsrSwlD6/tdF63jeXuvyy+cp0/TDRQHjNn5K+YMA0DQSbFsy87nWbNdO4ToLNzsqazq0OzaWTlSD0UPCIlvDhNLp1qdxeHIiGLq61LFhue38mHafpEPTDXJcyJwvVaHOuzwE3Jz38OopVQjSpZ02imI9B1pkT3gaOM21xsGtaty1ouVUXzOuTlMZVsMtp9go9TptVfrWH/lJw/q8SLBqlRHSs566ZdG2F/kYnKVWmgWD2amOm+ehrQtmoV9bFeFV6diwAcySUaMCLeqQsoGNTIFehc8IgmUrdkxNSG2O053CCduGai+II9A592YVRHVoEgLRpD6lLVb0Cf3Sz665zrNYuSYkRbfckGirvSqf1lHOuzewIoH3Fp1TkhWWn1a5mpoMxc+37f8gV8HiIEOPGl88KH0TNIoWAGFdfpbTcMinlmpZ/7QLdFCkszCAmb/PgupY7bgS0YM1xrdyK/Mu21XLDLVj/GPm7pD/nnfr1sUu+hZTwFUJ8zAkxVzvTjq6zTRc/iZZQHyx2hkIuZgG5K89tZRHiGjjM6AEKvPYolTKDuCc03y+DtlV7hAI24dB5j7P4TfgKGTlTvfzhycNNgJ8HxMgRuIjvjFVzI/IXxzA5Vx46LMJcYoQMFjNPxER5ikTb0vHj4VT85uPYwhfBmrBwJ8kykZkU+yTjeXhAr7iCNsOPDWE+B8WXh6QHoBIDx+fCPHPQ6KnnBdU=
  template:
    metadata:
      name: authelia-users
      namespace: authelia
