---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: technitium-oidc-client
  namespace: authelia
spec:
  encryptedData:
    client_id: AgCwsOn9kmazjTqFa3+x54la/AgxX4pUOw8Z3szGxmGc7Kg2myUVqLLXFohjEcIc0xqwnSW2E736sk5XXzvbse6YgTyu7EMPMV/+RL+qDGTGZDMKZKTq4OYemG3JWu9uZbuU1vMLkhrVroIq7ombkBDzvCDPQjZJIFxquQeij0GrUqAxgxKu04i42CdAHTqZegTPLgszpYE0CphvGcJ2Ko89ds4rVEm8xokfIfl5yj7YqHUfWO/Toso1a7uotmU3e4ME66vKpI/dP2IwiylHn7qUpXYttascqJTET2xII/+kJBRs9AhQU5+Tc0iJRK0B1sebrVfZjZ9Pzw9JtmjF60eBWjOdh/MG6+01lDgsOXfrods/IOkmkYBwAoTTZeZrFfD+YyXF1d0evW8ec12yo/GtMoK4ubY1nPxWkcvl/2ky7qEJsvJj2hNYqdhzRrjgdgKtE4T0dm+6lu57LMtzbuTrVl5Qzs0NsnIiZI/YwOPhMHAzTDp931pezpp0hMNggsmcZzgh1BXVJoT6ROiorb2FBRXxqri0YpSglEz5ET1udrnQTH97WnXDRKGk9JfKkUq7XUojxKwtj/ldYUJhA6jH2x1pm6GDvL/Qf6aiYvGzQjQs7v10JeB01wCY1Av3lunLfJueBZSOzLfq4ZnpoIl6slX0uXguGQTGnbO0IRaxq7+3ijolUP2H2AAHUN3DYEsit8ifHj9Ua+m+
    client_secret: AgBHlFZ3kSHzjFUPcoMUW8eUVLOXIag8jGUWMiGHCNaKdUnhh9mLNhgvAW0Ml4TWCCBx8bUa20jpn5825w6aXPiYn8vYsk9OFQbsTb8qcsknivfvBBal9LKJqepMOhbHy9l1XXauT9YFOtoP4fIujl/fmZao2KpqNu/caefiV95tqMW9nQDSOLjvcHsh3crrUm5f4TIpQ0ssBeYCv6pO4tG8iWoMmPGVs0S9Vffpa6HCWNXRlQq33pwcLm7mNqAs/MlELA9UaWJ8hlkOT7hJQrOqV9GODQRfdLOuQJR5cnccd7rVRDUIF+FBEJYLG0AArAWKj2eHA9yRn5WGm3QAYp697DJB0t/OERbSBQqbZqrwYrIIiTzTvxoSDiLps/0vIq16Y5cR7FHoQfpk+en1AKsSPvFaiwIRUJ19P+KxtBCW+xnfXixLtR0o6QiL+9x+9xNFLC9hihzSSDS4VtFdNHp04bbhH6+8GIuvV1wI8g5enhT2gVEgYlPfMhEOUTXQrxsXFPrYSnZZFOh6tQm/LwZ2ig3wT5v/e62tUNCbObuOaTI3hVJMN6Lii0oNyia4OMnUU0UZC7kgpNyDiQS/i8tAKTv8xzfTaq+i4faEvdbAxC8SpDGM/N7HCrbBj6RqBs7hsEj4m0eEvTvXN2JsOnyOF1CmX+0MqZpUge5fsGFTdcEhmPRXmhTXf6LdWNTbaiN0mLC7Tb6XZKR/SA5hLGvRyTTxky+qBIp96OcQM92vmK5FhNDw0dX/vSIu2vs88X0kiHJcr6nv8Ijfc75E3836
  template:
    metadata:
      name: technitium-oidc-client
      namespace: authelia
