---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: mount-options
  namespace: kube-system
spec:
  encryptedData:
    mountOptions: AgB+nYDtkxDuEYdZTg6f/38dJCWPFR8DEyE9lNd6hNUy5PDD5oR7uXp8WepbUW1GEdAsNjlS0xVpzE55lKkVLc9/JJ4uxOxrHZIHzLgOCPQmMFdkUKfiJs6apUdE2vvKN9PHTAFXAJ9nPmfHKdgU8+wnEbFb/15fP82U5kjMpd7m54YWS/6egg1UnJaV0hKSuGDLinpzJn8UIiR0F+D/TEFr6IAqUWuvMT1dfoBnfux6QNJ5SrbkC4L2xRLro27xNMcamtD+hbbNd1Vk8/sbJeduqE2qJIpZKcJzN+KIae5NFLwddpycBmLf0WS6Lgh/2NRbVctAJICchSjK6DlVPXky7pO/eBoh2A6pRvQdtMDXyyoT59XYAKUDU7u14x6NpCyb14uEpzFhyDqoqMBZ06znb03P6CHtPX2WazgxyWGVv0kX6xgLikMlB/jNOQ8WuAXRnn0JYwrk2DR+Y0xU3y79LuuQ3jTnkE6DaIZ0Vgl+daQBSJ4Rs4scJDUlkksN6omDvDvQjCqZ1OzpR4POhjBUeZrQvVNBu2ROu+ogl27kFPgVk4VZ2r5i8iRNEVFie5TOa/R9RX/WneJoV3f3f3OBAJTQje9bjJXk9QIO7dWa5+GuvBWuJ07PrORXm2s6WqzRxJ4WxTwjV0HUGYzJ+mbHT6BfX1t1Hd36rfotT6Tqe3+iNdNST/7DnscIsp0atB01fDageVtg1WmN53NZ3g==
  template:
    metadata:
      name: mount-options
      namespace: kube-system
    type: Opaque
