apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nfs-client
provisioner: nfs.csi.k8s.io
parameters:
  server: 10.0.0.23
  share: /serve/k8s
  csi.storage.k8s.io/provisioner-secret-name: mount-options
  csi.storage.k8s.io/provisioner-secret-namespace: kube-system
mountOptions:
  - nfsvers=4.1
  - hard
  - noatime
reclaimPolicy: Delete
volumeBindingMode: Immediate
allowVolumeExpansion: true
