---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-api-token
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgCUQrI1Z6TIPk4C/WCJOPIT5dcpNb+YHp0WO5TmAIxMGuath8iyxdayie2rYvMnyYbMHPT8hR5X7qacRTcCeLhWd4PK5Kjj5aIJGnOCPEwVbbUCaX6QHyHxBL0Jg1VO3pIn37nFU8l2yI5tDyO5UcymE8vD9Gj/Vl6lFo7g/BVaWKncxgfNEYEoYCiDP3Gy1VXJYyG24cfjJiPrn1DzFln4bNj58Effi40yS8IRchUuTyojtXK7g15y15Exf4s/QwmDcVlZr4SrAiGKZ7wqv2wlgoqYyFrxnhHJCAvdQXGJoq0GnByTcEX1lB7sgwl02ZzMQNf0eCJDXOttHvpfzNm5iEpKWS++8fiGDwlczR0afMDuo01+xnvPpVPe9qrEc1iJAqxWQ+KUxATWvrkUdwEIgCMXcGJ6N/tGybBR/pdSq7+A4kflhAtQqRTIAZtEvk9ceRmlVryCdJIxo5H9/xYUrwqPi6nkSCbcSInXIE/Kc3N+1z1n12/JVoiSAdIxr234P9y7noZoX4DwRtIEIozgA4wv/vNmCCfDobJQ+2MOk6ypeWPTX0VeusowJfJkI4i/iMaenfKDSoca2xoqCp3/8br1gCnADeIulFd22oy0VvDMoPlBFXe+tfQ0dp6WzBupiVIic7fe98h3HksTLjYuSukhT8DKIvhBaX/5TfGJepT0/ZYcmp5raVbDl+m3abljR4Q7IPFMxcSZ88pEZF6xqTppyWEQ8XqdZR8XsQExgs0KwEEUJQOBXt+9nZeS8fBOUUu6Wg==
  template:
    metadata:
      name: cloudflare-api-token
      namespace: cert-manager
    type: Opaque
