---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-api-token
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgCC07MtagdxFx2VINf4ggZaYDmu/zCc9aMfQ6ICr4vRcEbCFWhMfLwqboKbAPQKob1PycAod4q3hoChkerQCP3SiN/bMetznFIa5Wcu0A3nsVgp5chSvgf7DEbFmNaEJvhOCsm77Y4oDhgf1YPa4PK4OJPfFiZJaBODCBYxQpgqGAZBxCCj/bHoJNeGABY68KU73o1vpMFuaVPWLzmxCn2Scs9h1p5h42g8JqNpATH9//i8F/l3oybHGMWte89StLWC2ArYQitux3n+ycKV8rsVUCvFBzOdIn553RlUicwqTGmYfXkmraEzj0dyFUWbGypH54NPw25jk9Z/Fu31lfjUQ6BUHSVd+pM24HhNNRHwaKA9WWjkm0QDaWGtyY8c4Xn/K5nkaMC01LVtMO+nidiwxcMWEWkkexi4Kv1M5ssHd2MgC7UopqII3rKigjs4pcg+DKMkn1F3L6BkeYMVBDpji+XoMmjs0g2BXVm4u9UF1jNgMP6M3y6WfSSrfHgZp2M/UNVLDIRKXyl+qTu8HVv7xGBARFUUHYU72UI6iPTkDE2E5BL3eMAkA54u5CFvqAlIeGy3+w/9TnX4aLotImQ4ih+FM5nysAOJTVt4DRtBmS8tUhXa40nvpvIafYNOqJjpDT4upEcuh1PhTEzsTgOIFg7l+N5bnEwqTAWnkN9h+AsvrO2oR8CZ1Ml1hLkUvK7hP4YxR5AnuhfqXPqHke3S6kIXyG6VdxpY6jLHOT7GbyWorMf4k0u3eYIXUEq40+aWrC5zPw==
  template:
    metadata:
      name: cloudflare-api-token
      namespace: cert-manager
    type: Opaque
