---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: loki-basic-auth
  namespace: monitoring
spec:
  encryptedData:
    users: AgBbfa7r4no2iLauBDW8LzA1zz101a5BXzNIDneFh0O7ow7BWWxAQHjc5qAP6DftOPfuE8gCkV9EWOCyo9kDU/RcjAXCzjwzjd2CutQrII8xdX6cx3yGm71yGCasdam/SBJF689myyJN2L+AJKmREdtQDbBzsxKsTsPRIUiEm9hFp26BEMbsjp2UUSarmKTaPyhR3QUHX+SlzPcldZhQ3oK9e1nmiwy8rxRhKaWqu2elLN+PTwDSbDVXmDhqBB32zLT7eJIEff5YrgD/Pf7S3w187Qkbr9BjixhCqa+n13lqaB3Fchwy1obUjyM5uBzf+bzF8HAsVfO1dMsYaHV/75lJenT/rzoQLEm0MIsuok7tBTNksBfIXs+6YvEBIPBGjVH/XfTc6tY/yJETmgvZ+0rR+UQ7nvlAmpKQ3QkcZqZg0JrrYAsrPYRvx0KQ0/102fyCYCGDQuDN1P4FDcIgM/jV7D2zx2WWufyq34RTcjzk0vpY9JGrfxLW3Gsjke/BouwVewWkL5BDUVw6IZ/axH0YcfMoqrD59WfP2SARMjbUF/k3PBoTOk/XFlQMyaNAHNRJ2p2cR2PzcLooUybYb2brGFF/3C0/cSLubnO8HxFMLhgumE8WaztMNc5zxDiLev5x7SVALIalqsA0f9nVE67VABwqKZa9Fz1cRH0iT1g3Vq9icQTva/2QTuw+ZFgE5ubUuwL5uc1gA6V3S/kv/vf/MPupoklL3u9judZaAmhFrNZMNC6ZQuq3ffdp5YU1fpmq0oS+NjSQfUzJdvgyT9ilCh2/
  template:
    metadata:
      name: loki-basic-auth
      namespace: monitoring
