---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: plex-claim-secret
  namespace: servarr
spec:
  encryptedData:
    claimToken: AgCeS7s++3oOE/JWX/8PbX/ul5D3lHGWYeQHcUSGj5mIx70PUYIBP+d5mLRH3IcEAL3qcmFU3vXx6D4h5fQjzY2lxM9S+Tgr8IObiMaAtKuGtE0gkUFAQtuHvyvQ1f7BlgGRiWqG+mzLhtdR8Z3c115Es8M+Ci38ghZch3u+myBtY29epiBMcVhowpv/LwFldNwdOOzTJ+ytHjcwKcw6Px+lpA4Npfz4zH8CVMedmlzeeRC6jyMflbDlOl16TUWxkLL8qckZw/T1HR5AmSqfSlAG8wCM4orV2xT4c/m/oxhtSUnBRhWbdpC/QLYdd9kloIYHauNJxcqh8Zal7aiKBWqLhOV2b8OSiHxgVSAY6MCEKEOnkh+xFFyqRDA9FUodPojwb48r7yA8eNWBzgXQ5U0e1hwt8pcqUTuskz1nTJb8Ad7cTkllP8WQHzGA7JTDGngS3ORYW9VESXY1hh4NN7iiwKveiGk1XNEqjt2JP+9upxG21iSxO9fGWHRX7o23NpRpKJHd7lHCNeD7aQcSn2Ce1G7N3S7YNySie5N4U04uP6+l0uxm9rzi15o4ZCeIxfM8bNjJm7hT59RNJqwC3HC2RNVmckIJXIbHN/cDfAi6Yzx1zsNVYVuteJ/KjBRD4XelGxI/vSRU/cSH6MeRw3hiXIVKv3C7xPPeiEXCebO7MwZQH4G0Mg/M6pl1PDYkzxQCaDxE862IJC1y+FnOlLamHiS4WUjqYfx70w==
  template:
    metadata:
      name: plex-claim-secret
      namespace: servarr
