fullnameOverride: plex

controllers:
  main:
    type: deployment
    strategy: Recreate
    pod:
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      nodeSelector:
        kubernetes.io/hostname: talos-worker-1
    containers:
      main:
        image:
          repository: plexinc/pms-docker
          tag: "1.43.3.10896-cb3ebc72d"
        env:
          TZ: Europe/Ljubljana
          HOSTNAME: talos-plex
        securityContext:
          privileged: true
        resources:
          requests:
            cpu: 500m
            memory: 1Gi
          limits:
            memory: 4Gi

service:
  app:
    controller: main
    ports:
      http:
        port: 32400

persistence:
  dri:
    type: hostPath
    hostPath: /dev/dri
    globalMounts:
      - path: /dev/dri
  config:
    type: persistentVolumeClaim
    existingClaim: pms-config-plex-plex-media-server-0
    globalMounts:
      - path: /config
  cache:
    type: persistentVolumeClaim
    existingClaim: plex-cache
    globalMounts:
      - path: /caches
  transcode:
    type: persistentVolumeClaim
    existingClaim: plex-transcode
    globalMounts:
      - path: /transcodes
  data:
    type: nfs
    server: 10.0.0.104
    path: /mnt/serve/starr-stack/data
    globalMounts:
      - path: /data

route:
  app:
    parentRefs:
      - name: traefik-gateway
        namespace: traefik
        sectionName: websecure
    hostnames:
      - plex.talos-cluster.local.obleey.com
    rules:
      - backendRefs:
          - name: plex
            port: 32400
