---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: plex-claim-secret
  namespace: servarr
spec:
  encryptedData:
    claimToken: AgByQLPVn5NiiQsyKeWMfF95wVHjc8m1xb+skKn7EG/WHRAopDawaKFEdynWyw4eU8GkDN9MsXF6JqUf6YzfCkpno+HB2QVLHo2pv2l5j3lpM+yXCGq8Bqqxy3iKB6FbOABMTCvgw0cExlrUNKRt6ncNiLDxOcV2iGhos11WGbahBDKhycupMAbhK1qEY+Hwee+1Kz4OG2lB7lKTk2JTuTQhkNHTjt9mxGlDzGv/aIUndpSQ6hCyN0ZE+7Fau8p0t34dvhLzjazKxtRfGQ4VK5PDJVTiQeq2GhjX1H2aXUqbH4xK3j5jrYN9PDI6KsBsDKC8RjsmEZ0cUNMzqP0ZMRb6vIdnY/6AAah+G5wJarTnRqx4TvKr8IoXH1EpHL2K/RfnGGOzsgr2rIEmY258IfSIuneacjJS5pv0nDKDY4lvADCu+J4N+Ie/AIkmXNtyEIL/ypd5i4zv46QWXQLHTx4E2c/5EHTH2ZhgFt0kNuDace1g9FqpugdOZR45uf4W4Je6uSZkAYFVsHV65DVxVPopqPKvabed4TqfX3vaQRcDVQd8L5WU4Rruo04D8Qv9UCqXerGk2Ky1kfDdirmjpKJWV5GnQPmAPoq2WFBrMkcYi5X4spKvZ5foGCCzQiUjb0FAVMNq4LQTMlCiNu1tPMJ7s3rV9xoGXVsW1VGiP5oyu7z8BKNu/FHgTZTSdrOmOlAXugK7e5yBLApCOOA4+iEhow+vUqZe57aEtQ==
  template:
    metadata:
      name: plex-claim-secret
      namespace: servarr
    type: Opaque
