pms:
  storageClassName: local-path
  configStorage: 50Gi

  # hostNetwork is the key to showing as local not remote
  hostNetwork: true
  dnsConfig:
    nameservers: []
  dnsPolicy: ClusterFirstWithHostNet

nodeSelector:
  kubernetes.io/hostname: talos-0z8-aw8 # or talos-xxc-2bm, pick one worker

rclone:
  enabled: false

extraVolumes:
  - name: servarr-data
    nfs:
      server: 10.0.0.23
      path: /serve/starr-stack/data

extraVolumeMounts:
  - name: servarr-data
    mountPath: /data

service:
  type: ClusterIP
  port: 32400
