---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: plex-rclone-config
  namespace: servarr
spec:
  encryptedData:
    rclone.conf: AgAAjivFkPjLIQYgwgbbM/c6HKE4mfqwSVF/9Jtem4hWWIpOeJg01Fyor9CRJqiqBFuZySk6sxuPu9YUcLY672IrWI+um2qAXTx/Djbkuy31DTyTOtoVAg9dkmJmqxe1k3DfBhQWz6axpATSIE9rSjXN4ancfs41yj5EvZQ0I8Uvi+7n9uK6TEszZ3EOychD2Hr7WxHWYBAbFHZnz+PCjyjr8+rMi81K9gtk0NVgZ79omHILYa/4XabMhM3RG1Qncrvdk0YD3O5LK7A9kLckNTpFojxHkk3UJwj0/EwhdrdyJTAKYcEP9YsoNG8s7lMECpjI9BfxLz52HayC2MTsObXzqGUnfL1QPPMG43RgVyToavhsYNHUEuWRewHa9BTuV89ski10oU3RQxh+/fa+SdiRhHGZdkWoxS7K2+9YFFlxVV07GD/GiSRojV7qItGsd1PwQFKFdT8Lkdzznst0NW5VjS/6kYhPG37O6ZZgaPRvJkoH20ll/TY/dkYjIdE/4e4c1mB3Yw0oz5xqC7tb44XFgP8698No0ICp7HiSExv0brPvx2ThAEIGGYX9MTQCjLyA+qmn31rmnCDqIPmAxMmQaaILV2sN21MqyoRWCVT371iRb6kM5grts4awUJQQJ7gN65FJnk8wKRtnzPk1UYoHXIZw1+/R1H84gIkXjWsbFuxiIAl98uARni06OJ0PtwbItNziTB/deF88farpmQCm2hikIDsGHWyEpU3SuYNRFpBRhD7iBy8Z2MyWZvA+rs4wE29/XMl0/RinjBzGHUUCdg8=
  template:
    metadata:
      name: plex-rclone-config
      namespace: servarr
    type: Opaque
