---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: plex-rclone-config
  namespace: servarr
spec:
  encryptedData:
    rclone.conf: AgCJkkxCXuXH5IiFUr12JgZlHJfu2A9fOxAyYo2ggyKAy5whNpIoUzExxOhEwRrRNsH5KQeDq2iXhP5zj7DmCFtx/y7i2p959ODsLp9mVhnVOQoWWXQqSUTjSSaPx+4iQ0Ejty14jwYqNqDex7hthMpqsACQtcyjk4NHyllpGwSh5dUt9tWYqEQ68jJwdqz5L3nbseeCRR5yii/ggI0oGhNQl2Bp3PLubZirqYoMC4hTjbosY6jfxP+mz5W+u0jU5dINInZmxEfv0YaHRAAOw6J2w0S+tXonv3kOpmvJKEOiuAiSu+WJEgmdv2kV2ly2sDxGAyycDeS7eJ7nqtIOZnqFdW0IMJMuywjGjhASPfskrEkYBU/Qmo5uI8Iyatn3DYqu9vtnf6NzH04oA/JGPDiwqSRztwiLpb61DNTIPI9b00s68CQiB4hW0O+xidg4ovN7j/ldGA098HNoclvW1GylIO8zC8/e1TxRlVFLawq7tO5/ecqH0WbIKV6uoMZ8OOFf4UZ+r85CvIS64kjB9A+6rGGZD57wQFUhhdz7eGZwmtgfUyr9vTAW2YODGP976TRB9fUcewrBthua5aMDhIeK8Zhylw+qwT2wIn+nm/avFyEBKz00gi2ZuTf+0Vh+YxzTomYGshlPf2ftQPPsuyhL/IrSA3ExDI40fYZeYelZD8Age6DRn22QAcwrIscszt+3bGRSc14PFK0YKjtPv6B/fMUkUzpke+d1vb8FAL7J9b1R0Lgfjw6WoblY+mQ5i9zG2x7RsNDct6Cih4h/y/OqeR4=
  template:
    metadata:
      name: plex-rclone-config
      namespace: servarr
    type: Opaque
