---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: plex-rclone-config
  namespace: servarr
spec:
  encryptedData:
    rclone.conf: AgBoyQq2JOBWDhiFNibHrq+FFPxcDX+CG3VnlpAJLq9kumdN4GP0H+yC3gp45wSV9PI6Pzv/yfnqMHt5Cy4vvQkxaUfp71hbzYmtYpeuNbRGoponBmHLgu6yQxuP54NKv6CNcpHcQRLSxJI5pTgkbWEuCXkPIZdlnr5ZWLQOoCouep9OYZ4Ks8YPDuKyj+28FACIzcdAAsqLXUUT/sgf1bC8ry8liso+rQa9a/pO1ntTzowXnE/d0JafG/a/uAVwHeYeaelt7GwkPdecWeGoIC/Eku2AKS07uICV58yVwZL/yG6W9hEL3x6OBAnyNpupmNyTqlAJiNgIksVldbm8fC2ykj9SQfzchb09t9RpQHjVsOedVcum6rsoCWqJ+8ck2EY9kBc+3Uat6vEMENTn0RyzR7ZGut7nG5t0VKR+tYU1Nrhr6gWImwPdA7tK3UXkcLIqa63CG1XbdbtXKgX+qJ5LUh5cVWu7BhVmqPZlNJtbcZvWU++phbEO9qR7ASPfXng6RwHDLAd+lksp6UPWF4e7WOkgoGoDaFnMFY0urZ0iDeutWF7ia0kYT4ft2PjiDKiIH6yoXCQJmWEUaDCvL6CLuDEeU3NK1gBND9eVxlDfCyvSejO2HaRyWiutunnZlDh6EwsHXu968Q3/sNn7i78fo9Yvq2eD2oZ3Cjbp4F2E9AwF7Q+20CkqJZVueacdAiJaUdwOcT5LevEq6lCopWiN0dft44FcZmrPoD4SbIKrWSnWKpZbW6nuoM5jmLSsUfahXFZW64VCvL7hNtBUq3aj5VA=
  template:
    metadata:
      name: plex-rclone-config
      namespace: servarr
    type: Opaque
