apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - kube-state-metrics/app.yaml
  - victoriametrics/app.yaml
  - victorialogs/app.yaml
  - tempo/app.yaml
  - alloy/app.yaml
  - grafana/app.yaml
