apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cilium
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-4"
spec:
  project: default
  sources:
    - repoURL: https://helm.cilium.io
      chart: cilium
      targetRevision: 1.19.2
      helm:
        valueFiles:
          - $values/deployments/infrastructure/cilium/cilium-values.yaml
    - repoURL: https://github.com/obleey/talos-homelab
      targetRevision: HEAD
      ref: values
      path: deployments/infrastructure/cilium
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true