fullnameOverride: technitium-secondary

controllers:
  main:
    type: deployment
    containers:
      main:
        image:
          repository: technitium/dns-server
          tag: '15.4.0'
        env:
          DNS_SERVER_DOMAIN: dns02.dns.local
          TZ: Europe/Ljubljana
    pod:
      hostAliases:
        - ip: 10.0.0.104
          hostnames:
            - dns01.dns.local

service:
  app:
    controller: main
    ports:
      http:
        port: 5380

persistence:
  config:
    type: persistentVolumeClaim
    existingClaim: technitium-secondary-config
    globalMounts:
      - path: /etc/dns

route:
  app:
    parentRefs:
      - name: traefik-gateway
        namespace: traefik
        sectionName: websecure
    hostnames:
      - technitium-secondary.talos-cluster.local.obleey.com
    rules:
      - backendRefs:
          - name: technitium-secondary
            port: 5380
