fullnameOverride: technitium-secondary

controllers:
  main:
    type: deployment
    containers:
      main:
        image:
          repository: technitium/dns-server
          tag: "24.04"
        env:
          DNS_SERVER_DOMAIN: technitium-secondary
          TZ: Europe/Ljubljana

service:
  app:
    controller: main
    ports:
      http:
        port: 5380

persistence:
  config:
    type: persistentVolumeClaim
    existingClaim: technitium-secondary-config
    globalMounts:
      - path: /etc/dns
