fullnameOverride: technitium-secondary

controllers:
  main:
    type: deployment
    containers:
      main:
        image:
          repository: technitium/dns-server
          tag: '15.4.0'
        env:
          DNS_SERVER_DOMAIN: dns02.dns.local
          TZ: Europe/Ljubljana
    pod:
      hostAliases:
        - ip: 10.0.0.104
          hostnames:
            - dns01.dns.local

service:
  app:
    controller: main
    forceRename: technitium-secondary
    ports:
      http:
        port: 5380
  dns:
    controller: main
    type: LoadBalancer
    forceRename: technitium-secondary-dns
    annotations:
      io.cilium/lb-ipam-ips: "10.0.0.201"
    ports:
      dns-udp:
        port: 53
        protocol: UDP
      dns-tcp:
        port: 53
        protocol: TCP
      admin-https:
        port: 53443
        protocol: TCP
      admin-http:
        port: 5380
        protocol: TCP

persistence:
  config:
    type: persistentVolumeClaim
    forceRename: technitium-secondary-config
    accessMode: ReadWriteOnce
    size: 1Gi
    storageClass: longhorn
    globalMounts:
      - path: /etc/dns

route:
  app:
    parentRefs:
      - name: traefik-gateway
        namespace: traefik
        sectionName: websecure
    hostnames:
      - technitium-secondary.talos-cluster.local.obleey.com
    rules:
      - backendRefs:
          - name: technitium-secondary
            port: 5380
