apiVersion: v1
kind: Service
metadata:
  name: technitium-secondary-dns
  namespace: technitium-secondary
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/controller: main
    app.kubernetes.io/instance: technitium-secondary
    app.kubernetes.io/name: technitium-secondary
  ports:
    - name: dns-udp
      port: 53
      targetPort: 53
      protocol: UDP
    - name: dns-tcp
      port: 53
      targetPort: 53
      protocol: TCP
    - name: admin-https
      port: 53443
      targetPort: 53443
      protocol: TCP
    - name: admin-http
      port: 5380
      targetPort: 5380
      protocol: TCP
