apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: technitium-cluster-tls
  namespace: technitium-secondary
spec:
  secretName: technitium-cluster-tls
  issuerRef:
    name: cloudflare-cluster-issuer
    kind: ClusterIssuer
  dnsNames:
    - "*.dns.local.obleey.com"
  keystores:
    pkcs12:
      create: true
      passwordSecretRef:
        name: technitium-cluster-tls-password
        key: password-key
