---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: technitium-cluster-tls-password
  namespace: technitium-secondary
spec:
  encryptedData:
    password-key: AgATzHgf9yV6ATbzgkwkA7rbvsfLHAmubf0McYOLyb8OhTa7YMW9Cv3crrkxFk0EcxvE0gAFCBlfamFlkdY+32JjDszQyBYN5FL0ZKdwEKk2eafEw3Zu1RL4oKZaCNOGQylK9LhlW61geLtt0kmYGSlHAEscpT7YmimAhBf/98vPVsiO4BG2wM9Y8DCdizBW0bpLJjiKP4gF1wGNwUuLPDS5evMjX0rlvIOI3VPXbUBKha1r66P0etRBcocVz94Tv11dl632Nh9Z0ghFy+XpZyKCpcV9uOvpiy1q9MbihXd0dR11HBsFARx7IIHY1qQ5tlg2Bxw7RS1ZJgjOwkaVYVXl1XKYiL5SsbeaDJxfxAxDaem0zvRGqwuJT6uW7fC/nEjbaAr1n+uZ+xatguHz9AfFdqyohFxyx6n+emvXOt5ix6WWrjuBuALgQW8lRWJx5W4A/hi0adzvaXzx1MkMvjpY5FxdhsQSpYkWNz5hiR463Oi5CGFEI3ddDu0SBbIwskxGBgDddQUmDw9uaFRdoeILHaz4TiHmr7Umfu6SFhUllbT2krKx+2/gFNqT1CBnnQW9Xeb++05AseXQ0J1FiVcZFa5gYnW+Ss2t+pIjX8kAHcAT0gOg5gFGqJx2YyqVc58qLj7xsBWoOJ51DZXCW64I40bqcZ+PZFHvxkwO5Fvc+98JYMXaLAqRc7pJcGwp1bXtvkGcpzkB72bknX5RSptbccpcaAEDkv0=
  template:
    metadata:
      name: technitium-cluster-tls-password
      namespace: technitium-secondary
