apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kubelet-serving-cert-approver
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://alex1989hu.github.io/kubelet-serving-cert-approver
    chart: kubelet-serving-cert-approver
    targetRevision: 0.8.7
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
