---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin-secret
  namespace: observability
spec:
  encryptedData:
    admin-password: AgB+Ax2rvIEHp6tvgtvgOo4HLzGWI0jpPUp0duhnp/NaY4IfdQiKAgHkpCiasN+gaHhj8vFgpkUCPFLRX12ZFTiaZF5nbM4ZxjMFlFfQD465Dl4RS4TAx1ZkurMS73/00bMRoEVTtgEUFv2g1KMj6vYXrbrQVfGwB6unLFZF2Q5yGEmpvCntGo1rgn2BQzZ6i3k6eg1MNuWCmpflxDIIJezoWFHiekDhExmtAY6jB2SJciVMdDx4M1SprWUuHyokp8UV5++Pc3wnwQIt2JYOFQaD8hmhR1rosPaTW+B1JiRGt2W/mpxmh+S4rGHSiDNnReaIu0KkUWEU7cwaeGGgh0LgRIuwO/3BCAiB88CFzafFlRRMkweUsAHwVdC3rFBYxqVfEU6ZbeF7o7pFIoj6dddXPDGGwBZYmL9SQ9VdooboTHICjJ40RaJtRENAl8Tk9waMaQdFbcXsAUD5T7ksz7IR9TdI9eHPD0m2Q0JuleBr7/16uciQzuxDapUUUJuckPKL9yBAOd+ObMpamvpFMCcqPo8bP5M02x3Fl3yVK7fIVPWU+F2TZCwQDVN9G50mq3iR5Q16NzlR5IugFIL/BuEhAnDzYy3sEVqWE+t73xMQfhtuLC3F8FQmF03SgiGMVqE0+98s6nCjAucCvhRhQt6mgqPMvAnE61B28m9HTCrPMRDByGD6GhyI7TnZY3FSlxiZB0fm1lDtHVOjM1YVvo8WedyAB8k6PEE=
    admin-user: AgC1ldr6LV01S56uLtCHxrZIkqPM5hxhPspFZO1iGN++j598lT5gBtikfT8D6yHX2gcSQXl367p5xWTVXH+iahnBwQ5JMJcoWE+CK5KEwYPtng7sxOiDG1AdsncpN43GdgPjkuqbmqTq2ZdBCZqatX7PgqM/wJjZwpi4iP1pZK5b7J+vLF+PmedtUOfyQWqHM7pw620DsSj5KNt208IB/X1XGA56ouR5JBZBBZJqJx+NadhJWf7GWHpxPh46nxGB23YsrC7SbF5zZOPCidUhgWNdT4bkP1brOvj0QSmY8t18xyncAMxUfFFThYJUgX6uxMw2yx0XP/x3ZoFbnvosYJh2y+91VGt8wOPFbs/45gZZoaJtIGy6t3NSgzSBebUvqo3TV47Wml+IRUGz6aFYF2QZr2xJiQffoJpP2pJL0sV4VzYKcKQmcuWHWOR/bo1sqxUKi5RPInlGKqJCjj1/+/PoCq3ElwbH7xUI6jLtH/K3LFlsSWigC01ITIj7kU1JmiFWU0IeC9VucLdhagieUZyXTFsVmQObOd9Es7H5VsaOOn2agJzCLsKt7p3sFfFyMPY6gZZqxFCPhSXwED98YKizUYAz31CYADDMhZVnEvDr8phNI3150z0ZMb2SjrmLflB4hi0lzYVeXXr30WRLqdDNF6Z14qroBH/SNYpUjkCXKYWIk86JlKwFoyPtsenK+aicCHaktvA=
  template:
    metadata:
      name: grafana-admin-secret
      namespace: observability
